export const PERGUNTAS_PARA_O_FUTURO = [
  "O que você está sentindo agora, neste exato momento?",
  "O que está acontecendo no mundo, no seu país e na sua cidade hoje?",
  "Qual é o seu maior sonho neste momento da vida?",
  "O que você espera ter conquistado até a data de abertura desta cápsula?",
  "Quem são as pessoas mais importantes na sua vida agora? Por quê?",
  "Qual foi a maior alegria que você viveu este ano?",
  "Qual foi o maior desafio que você superou recentemente?",
  "O que você diria para a sua versão do futuro, se pudesse falar com ela agora?",
  "O que você gostaria de lembrar sobre como você é hoje?",
  "Qual música representa esta fase da sua vida?",
  "O que você mudaria em você mesmo, se pudesse?",
  "O que você nunca quer esquecer sobre este momento?",
  "Que conselho você daria para si mesmo no futuro?",
  "O que te faz rir hoje?",
  "Qual é o seu lugar favorito no mundo agora?",
  "O que você está aprendendo sobre si mesmo?",
  "Se pudesse guardar um cheiro, um som e uma imagem deste momento, quais seriam?",
  "O que você tem medo de perder com o tempo?",
  "O que você espera que nunca mude em você?",
  "Qual promessa você quer fazer para si mesmo agora?",
  "Como está sua família neste momento?",
  "O que está na moda agora que você acha que vai parecer estranho no futuro?",
  "Qual foi a melhor decisão que você tomou recentemente?",
  "O que você faria diferente se pudesse recomeçar este ano?",
  "Descreva um dia comum da sua vida agora, com todos os detalhes.",
  "O que te dá esperança sobre o futuro?",
  "Qual é a sua maior gratidão hoje?",
  "O que você espera ter aprendido até abrir esta cápsula?",
  "Quem você quer que esteja com você quando esta cápsula for aberta?",
  "Escreva uma carta para a pessoa que você ama, contando como se sente hoje.",
  "Se esta cápsula fosse para um casal, o que vocês prometem um ao outro?",
  "O que você espera que continue igual entre vocês com o passar dos anos?",
  "Qual memória deste ano você quer guardar para sempre?",
  "O que você acha que vai ter mudado no mundo até a data de abertura?",
  "Descreva como você imagina a sua vida na data de abertura desta cápsula.",
  "O que você gostaria de perguntar à sua versão do futuro?",
  "Qual foi a melhor viagem ou experiência que você viveu recentemente?",
  "O que te emociona só de pensar em reler isso no futuro?",
];
